- include/Event.hpp
- src/Event.cpp
Closes #29. Implements events -- callbacks scheduled at some specified time in future.
> Network Simulator: class Event

- .clang-format
Closes #54. Add `.clang-format` file.
> STYLE: add clang format

- .gitmodules
- .vscode_template/launch.json
- .vscode_template/tasks.json
- CMakeLists.txt
- README.md
- test/simple_test.cpp
> Set up testing framework

- source/event.hpp
- source/flow.hpp
- source/link.hpp
- source/packet.hpp
- source/scheduler.hpp
- source/sender.hpp
- source/simulator.hpp
> Network simulator: fix dependecies

- source/device.cpp
- source/device.hpp
- source/event.hpp
- source/flow.hpp
- source/link.hpp
- source/receiver.hpp
- source/sender.hpp
- source/simulator.hpp
- source/switch.hpp
> REFACTOR: Device interface isolation

- CMakeLists.txt
- source/link.cpp
- source/sender.hpp
> BUG: add -Wall -Wextra to project compile flags

- README.md
- source/flow.hpp
- source/link.hpp
- source/receiver.hpp
- source/sender.cpp
- source/sender.hpp
- source/switch.hpp
> FEAT: Implement std::enable_shared_from_this 

- source/event.cpp
- source/event.hpp
- source/link.cpp
- source/link.hpp
- source/packet.hpp
- source/receiver.cpp
- source/sender.cpp
- test/link/get_from_test.cpp
- test/link/get_packet_test.cpp
- test/link/get_to_test.cpp
- test/link/process_arrival_test.cpp
- test/link/schedule_arrival_test.cpp
- test/switch/test_switch.cpp
> FEAT: Implement Events

- source/flow.cpp
- source/flow.hpp
- source/receiver.hpp
- source/sender.cpp
- source/sender.hpp
- source/simulator.cpp
- source/simulator.hpp
- source/switch.hpp
- test/simulator/start_test.cpp
> BUG: Simulator fix

- .github/workflows/cmake-single-platform.yml
> BUG: fix gnuplot installation

- source/parser/identifiable_parser.hpp
- source/simulator.hpp
- source/utils/identifier_factory.hpp
> BUG: Segfault when invalid sender is passed to link

- .github/workflows/cmake-single-platform.yml
> FEAT: Add build flags for parallel compilation in CI

- source/flow/flow.cpp
- source/flow/tcp_flow.cpp
- source/parser/identifiable_parser.hpp
- source/parser/parse_primitives.cpp
- source/parser/parser.cpp
- source/parser/parser.hpp
> REFACTORING: parsing

- CMakeLists.txt
- source/link.cpp
- source/link.hpp
- source/main.cpp
- source/metrics/metrics_collector.cpp
- source/metrics/metrics_collector.hpp
- source/metrics/metrics_storage.hpp
Minor refactoring for the Link.
> REFACTOR: Link

- .github/workflows/cmake-single-platform.yml
> BUG: deleting artifacts

- .gitmodules
- CMakeLists.txt
- README.md
- main.cpp
- source/main.cpp
> BUG: Fix command line arguments parsing

- configuration_examples/simulation_examples/basic_simulation.yml
- configuration_examples/topology_examples/bus_topology.yml
- configuration_examples/topology_examples/fat_tree_topology.yml
- configuration_examples/topology_examples/leaf_spine_topology.yml
- configuration_examples/topology_examples/mesh_topology.yml
- configuration_examples/topology_examples/star_topology.yml
- configuration_examples/topology_examples/three_tier_topology.yml
- configuration_examples/topology_examples/topology_simple.yml
- configuration_examples/topology_examples/vl2_topology.yml
- source/device/switch.cpp
- source/device/switch.hpp
- source/link.cpp
- source/link.hpp
- source/link/interfaces/i_link.hpp
- source/link/link.cpp
- source/link/link.hpp
- source/packet.cpp
- source/packet.hpp
- source/parser/identifiable_parser.hpp
- test/device/utils.cpp
- test/device/utils.hpp
- test/simulator/topologies/mesh_topology.yml
- test/simulator/topologies/simple_topology.yml
- test/simulator/topologies/trivial_topology.yml
- test/switch/link_mock.cpp
- test/switch/link_mock.hpp
> FEAT: add ECN support

- configuration_examples/generator/bottleneck.py
- configuration_examples/simulation_examples/incast_simulation.yml
- configuration_examples/topology_examples/incast_topology.yml
- source/device/receiver.cpp
- source/device/switch.cpp
- source/flow/flow.cpp
- source/flow/flow.hpp
- source/flow/tcp_flow.cpp
- source/flow/tcp_flow.hpp
- source/metrics/metrics_collector.cpp
- source/metrics/metrics_collector.hpp
- source/metrics/metrics_storage.cpp
- source/packet.cpp
- source/packet.hpp
Closes #273.  New field added to the packet which records the amount of data sent by the flow at the time of sending the packet (as it is done in BBR).
> FEAT: Delivery rate for each flow

- configuration_examples/generator/bottleneck.py
Closes #278
Replaced types `sender`, `receiver` --> `host`.
> BUG: device types in configuration_examples/generator/bottleneck.py

- .github/workflows/load_testing.yml
- configuration_examples/generator/bottleneck.py
- scripts/run_incast_simulation.py
> FEAT: CI job for load testing

- source/metrics/metrics_collector.cpp
> BUG: Fix plots

- configuration_examples/topology_examples/bus_topology.yml
- configuration_examples/topology_examples/incast_topology.yml
- source/device/ecn.cpp
- source/device/ecn.hpp
- source/device/switch.cpp
- source/device/switch.hpp
- source/link/interfaces/i_link.hpp
- source/link/link.cpp
- source/link/link.hpp
- source/parser/identifiable_parser.hpp
- source/utils/identifier_factory.hpp
- test/device/ecn_test.cpp
- test/device/utils.cpp
- test/device/utils.hpp
- test/simulator/topologies/mesh_topology.yml
- test/simulator/topologies/simple_topology.yml
- test/simulator/topologies/trivial_topology.yml
- test/switch/link_mock.cpp
- test/switch/link_mock.hpp
> FEAT: RED from ECN marking

- configuration_examples/generator/README.md
- configuration_examples/generator/bottleneck.py
- scripts/run_incast_simulation.py
Closes #303 
- Added README.md with examples of using a `bottleneck.py`
- Added several switches (between senders and receivers) support in `bottleneck.py`
> FIX: Improve stress topology generation scripts

- source/logger/logger.cpp
- source/logger/logger.hpp
> OPTIMIZATION: speed up logger

- .github/workflows/cmake-single-platform.yml
- .github/workflows/load_testing.yml
- .github/workflows/load_testing_controller.yml
- .github/workflows/update-gh-pages.yml
- scripts/check_artifacts.py
- Added `load_testing_controller` CI job to run the Load testing CI in correct way
- Added `check_artifacts.py` script to check availability of deployed artifacts
> Update FlameGraph CI

- .github/workflows/cmake-single-platform.yml
> BUG: run simulations in CI

- README.md
Closes #398 
Some improvements for README.md
> FIX: Improve README.md

- scripts/generate_image.py
> BUG: image generator

- source/flow/tcp/i_tcp_cc.hpp
> BUG: Compilation failure with clang

- scripts/topology_generator/incast.py
> FEAT: Add incast generation script

- configuration_examples/simulation_examples/basic_simulation.yml
- configuration_examples/simulation_examples/incast_simulation.yml
- configuration_examples/simulation_examples/mplb_simulation.yml
- configuration_examples/simulation_examples/tcp_simulation.yml
- configuration_examples/simulation_examples/tcp_single_layer_fractal.yml
- configuration_examples/simulation_examples/tcp_two_layers_fractal.yml
- scripts/topology_generator/README.md
- scripts/topology_generator/bottleneck.py
- scripts/topology_generator/incast.py
- source/main.cpp
- source/parser/parse_utils.cpp
- source/parser/parse_utils.hpp
- source/parser/parser.cpp
- source/parser/parser.hpp
- source/parser/simulation/flow/tcp_flow_parser.cpp
- source/parser/topology/link/link_parser.cpp
- source/simulator.cpp
- source/simulator.hpp
- test/simulator/recalculate_paths_test.cpp
- test/simulator/start_test.cpp
- test/simulator/topologies/mesh_topology.yml
- test/simulator/topologies/simple_topology.yml
- test/simulator/topologies/trivial_topology.yml
> BUG: units in configs & optional simulation time

- scripts/topology_generator/bottleneck.py
After last merge request I forgot to update topology generator used in load testing
> BUG: Fix incast
